### ISSUE TITLE
[Bug] Adding a Youtube Channel to the Queue Breaks the Room

### ISSUE THREAD

**Issue by ceelman** [jbkuczma/moose#72]
Under search results occasionally Youtube Channel names will appear as an option to add to the "Up Next" queue. If a Youtube Channel actually gets added to the queue, instead of playing a video the box displaying the current video will say "invalid parameters". This breaks the room as no future videos in the queue will begin playing.

**Comment by Rmiller1673** [comment]
Thank you for reporting this bug!

**Comment by jbkuczma** [comment]
merged to develop
