### ISSUE TITLE
Join room doesn't recognize a room code

### ISSUE THREAD

**Issue by devnocs** [jbkuczma/moose#73]
Created a room, got its code and tried joining. Didn't let me join as the room no was invalid.

**Comment by jbkuczma** [comment]
@devnocs when you tried joining your created room, was it with a second account?

**Comment by devnocs** [comment]
same account

**Comment by jbkuczma** [comment]
@devnocs Currently if you let the queue of a room empty it will close. When you create a room, there is a 20 second window to enter music into the queue or else it will close, making that room code invalid.

**Comment by jbkuczma** [comment]
@devnocs also, we have not been able to reproduce this. if you could be as specific as possible with the steps you took in for this bug to occur would be very helpful.

**Comment by devnocs** [comment]
Yeah i did close the room without any song in the queue. So that may be it. Thanks for clarifying. I'll close this issue then.
Good work on this
