### ISSUE TITLE
(Bug) Overlay Div Provides Confusion

### ISSUE THREAD

**Issue by vanpyrzericj** [jbkuczma/moose#78]
When adding a song to the queue, the div tag with id `overlay` appears and seems to dim the screen a bit, but doesn't provide any user feedback on why this is happening. Consider using a library like BlockUI (http://malsup.com/jquery/block/#overview) to give more useful feedback to the user (eg that the song is currently being added to the queue).

**Comment by jbkuczma** [comment]
thanks for the feedback! we'll take a look at how we can make it better
