### ISSUE TITLE
Database bug: I can't register with normal username and the password.

### ISSUE THREAD

**Issue by QinxinTian** [jbkuczma/moose#79]
[Screen Capture 16.mov.zip](https://github.com/jbkuczma/moose/files/1443800/Screen.Capture.16.mov.zip)
If I didn't remember incorrectly, the username is the "csecse@gmail.com"
The password is the "Zxcvbvcxz" which I believe is very normal.

**Comment by jbkuczma** [comment]
The account creation failed because usernames can only contain letters and numbers and have a length between 3 and 16 characters.
