### ISSUE TITLE
Bug: Not selecting a music video to play within 20 seconds kicks you back to the room creation screen

### ISSUE THREAD

**Issue by Proplex** [jbkuczma/moose#80]
Steps to reproduce:
1.  Create a room
2.  The 10 second video count-down timer starts
3. The 10 second video count-down timer starts again
4. You're kicked out of the room and into the room creation screen

Using production on https://moosemusic.net

**Comment by Rmiller1673** [comment]
Thank you for reporting this, however this was a decision made by our team on purpose to stop people from spamming our application and creating many rooms and leaving those rooms open and inactive.
