### ISSUE TITLE
Was unable to create an account

### ISSUE THREAD

**Issue by hjkaria** [jbkuczma/moose#85]
Every time I'd try to create an account, it would redirect back to the Login screen and show the message, "Account Creation Failed" 
![image](https://user-images.githubusercontent.com/14285726/32443374-ce420a26-c2cc-11e7-8cb0-f8264e361dc8.png)

**Comment by jbkuczma** [comment]
What was the username you were trying to create an account with? The length of the username must be between 3 and 16 characters and only contain letters and numbers.

**Comment by hjkaria** [comment]
Oh I see, I think my username was just too long then.
